# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Somday' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FSCalendar'
  pod 'SwiftyMenu', '~> 0.6.4'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'SideMenuSwift'

  # Pods for Somday

end
